services:
  postgres:
    image: postgres:15
    container_name: forkpoint-postgres
    environment:
      POSTGRES_DB: ForkPoint
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - forkpoint-network

  forkpoint-api:
    build:
      context: .
      dockerfile: ForkPoint.API/Dockerfile
    container_name: forkpoint-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__Default: "Server=postgres;Database=ForkPoint;User Id=postgres;Password=password"
      ASPNETCORE_URLS: "http://+:80"
      ClientURI: ${CLIENT_URI}
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - forkpoint-network
    volumes:
      - ./ForkPoint.API/Logs:/app/Logs

  forkpoint-client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: ${API_BASE_URL}
        VITE_APP_TITLE: ${APP_TITLE}
    container_name: forkpoint-client
    ports:
      - "8081:80"
    depends_on:
      - forkpoint-api
    networks:
      - forkpoint-network

volumes:
  postgres_data:

networks:
  forkpoint-network:
    driver: bridge